### ISSUE TITLE
Clean up broken links to geoblacklight.org/docs

### ISSUE THREAD

**Issue by karenmajewicz** [OpenGeoMetadata/opengeometadata.github.io#103]
We updated the geoblacklight.org/docs site during the winter 2024 sprint and may have broken some links.

**Comment by mradamcox** [comment]
Found one example of this in https://opengeometadata.org/ogm-aardvark/#description

![image](https://github.com/user-attachments/assets/e6675450-df56-4932-a373-e3718b80d1c0)

change https://geoblacklight.org/docs/customization/rendering_html_from_description/ to
 https://geoblacklight.org/docs/rendering_html_from_description/

**Comment by karenmajewicz** [comment]
Fixed the broken Description link: https://github.com/OpenGeoMetadata/opengeometadata.github.io/commit/c77cd6465f1e9e3d2463eef762f2adf681d0de6e

**Comment by karenmajewicz** [comment]
ran a link checking script and did not find more broken ones.
