### ISSUE TITLE
Add controlled vocabulary to Format page

### ISSUE THREAD

**Issue by rmseifried** [OpenGeoMetadata/opengeometadata.github.io#53]
### Description of the issue
[GBL 1.0's Format](https://opengeometadata.org/docs/gbl-1.0#format) field had a controlled vocabulary, currently viewable on this standalone page: [Format Values](https://opengeometadata.org/docs/format-values).

[OGM Aardvark's Format](https://opengeometadata.org/docs/ogm-aardvark/format) field still has a controlled vocabulary but the list is not strict. @kgjenkins suggested we point to the original list as a helpful entry guide. 

### Suggested fix
Copy the format values to the bottom of this page, so that the description and the values are in the same place. It should look like this page:

![Screen Shot 2022-07-11 at 2 07 36 PM](https://user-images.githubusercontent.com/36506059/178329560-d0c2d0af-3050-4553-9ae6-8ec1c7209d4d.png)

**Comment by karenmajewicz** [comment]
Hah, where is the [amused groan emoji]?
