### ISSUE TITLE
Add descriptive text to top of OGM Aardvark page

### ISSUE THREAD

**Issue by rmseifried** [OpenGeoMetadata/opengeometadata.github.io#64]
Currently there is no descriptive or contextual information on the [OGM Aardvark landing page](https://opengeometadata.org/docs/ogm-aardvark) to let users know what this page is about. Recommend adding a paragraph at the top that explains this is a metadata schema designed to be written in geoJSON format, etc.

**Comment by karenmajewicz** [comment]
see PR #68 (https://github.com/OpenGeoMetadata/opengeometadata.github.io/pull/68/files#diff-63706e2750d05ebfc1fd9ab547b3490208ba94b57ed8e50e776b97bd15d19464)

**Comment by karenmajewicz** [comment]
We added text, but then thought it seemed to messy and just added better info to the About page. thoughts? https://opengeometadata.org/docs/ogm-aardvark

**Comment by rmseifried** [comment]
This looks good to me!
