### ISSUE TITLE
Missing "Georeferenced" section in OGM Aardvark page

### ISSUE THREAD

**Issue by mradamcox** [OpenGeoMetadata/opengeometadata.github.io#81]
Following the link in the top matter here: https://opengeometadata.org/ogm-aardvark

![image](https://user-images.githubusercontent.com/10427268/231541647-98756d1f-cb26-4d8e-9d85-d8299a358dd4.png)

Doesn't go anywhere... Looks like there is no Georeferenced section on the page for the link to go to.

**Comment by karenmajewicz** [comment]
Thanks for catching this - the link should work now: https://opengeometadata.org/ogm-aardvark/#georeferenced
